apiVersion: v1
kind: Service
metadata:
  name: tst-app
  labels:
    app: tst-app 
spec:
  selector:
    app: tst-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http 
  type: LoadBalancer # expose external ip address