replicaCount: 1

# This value is taken by default from Terraform
image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

service:
    type: LoadBalancer
    port: 8000

resources:
    limits:
        nvidia.com/gpu: 1
nodeSelector: {}
tolerations: []
affinity: []

kube-prometheus-stack:
    prometheus:
        prometheusSpec:
            scrapeInterval: 15s
            serviceMonitorSelector: {}
    grafana:
        enabled: true
        defaultDashboardsEnabled: true
        dashboards:
            default:
                llm-metrics:
                    json: |
                        # Include your dashboard JSON here
                    datasource: Prometheus
        service:
            type: LoadBalancer
