{
 "title": "4. General Performance Analysis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Request Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(llm_request_count_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(llm_error_count_total) / sum(llm_request_count_total))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Error Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(llm_error_count_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Tokens Generated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(llm_tokens_generated_total[1m]))",
     "legendFormat": "{{`{{user_id}}`}}"
    }
   ]
  },
  {
   "title": "Input Tokens",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": " sum(increase(llm_tokens_input_total[1m]))",
     "legendFormat": "{{`{{user_id}}`}}"
    }
   ]
  },
  { "title": "Process Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "File Descriptors",
   "type": "piechart",
   "description": "Percentage of used file descriptors",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds / process_max_fds",
     "legendFormat": "{{`{{job}}`}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{`{{job}}`}}-resident" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{`{{job}}`}}-virtual" }
   ]
  },
  {
   "title": "CPU time spent by the process (percentage)",
   "type": "piechart",
   "description": "CPU time spent by the process (percentage)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "{{`{{job}}`}}"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Python Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total[5m])",
     "legendFormat": "{{`{{generation}}`}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "llm_ram_usage_bytes", "legendFormat": "{{`{{__name__}}`}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "llm_cpu_usage_percent", "legendFormat": "{{`{{__name__}}`}}" }
   ]
  }
 ]
}