{
 "title": "LLM Metrics Per User",
 "tags": [ "llm-monitoring" ],
 "templating": {
  "list": [
   {
    "name": "user_id",
    "query": "label_values(llm_request_count_total, user_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests (Last 5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(llm_request_count_total{user_id=~\"$user_id\"}[5m])"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(llm_request_latency_seconds_sum{user_id=~\"$user_id\"}[1m]) / rate(llm_request_latency_seconds_count{user_id=~\"$user_id\"}[1m])"
    }
   ]
  },
  {
   "title": "Average Time to First Token",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(llm_time_to_first_token_seconds_sum{user_id=~\"$user_id\"}[1m]) / rate(llm_time_to_first_token_seconds_count{user_id=~\"$user_id\"}[1m])"
    }
   ]
  },
  {
   "title": "Tokens Generated (Last 5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "targets": [
    {
     "expr": "increase(llm_tokens_generated_total{user_id=~\"$user_id\"}[5m])"
    }
   ]
  },
  {
   "title": "Inference Errors (Last 5m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "increase(llm_error_count_total{user_id=~\"$user_id\"}[5m])"
    }
   ]
  },
  {
   "title": "Num Limit Breaches (Last 5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "breaches" } },
   "targets": [
    {
     "expr": "increase(llm_rate_limit_breaches_total{user_id=~\"$user_id\"}[5m])"
    }
   ]
  }
 ]
}