{
 "title": "LLM Global Metrics",
 "tags": [ "llm-monitoring" ],
 "panels": [
  {
   "title": "Total Requests (Last 5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(llm_request_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(llm_request_latency_seconds_sum[1m])) / sum(rate(llm_request_latency_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Average Time to First Token",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(llm_time_to_first_token_seconds_sum[1m])) / sum(rate(llm_time_to_first_token_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Tokens Generated (Last 5m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "targets": [
    {
     "expr": "sum(increase(llm_tokens_generated_total[5m]))"
    }
   ]
  },
  {
   "title": "Inference Errors (Last 5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "sum(increase(llm_error_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Num Limit Breaches (Last 5m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "breaches" } },
   "targets": [
    {
     "expr": "sum(increase(llm_rate_limit_breaches_total[5m]))"
    }
   ]
  },
  {
   "title": "Error Types Breakdown (Last 5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "sum by (error_type) (increase(llm_error_types_total[5m]))",
     "legendFormat": "{{`{{`}} error_type {{`}}`}}"
    }
   ]
  }
 ]
}