global:
  resolve_timeout: 5m
route:
  receiver: "null"
  routes:
    - matchers:
        - alertname = "LLMHighRequestLatency"
      receiver: "slack"
    - matchers:
        - alertname = "LLMSlowTimeToFirstToken"
      receiver: "slack"
    - matchers:
        - alertname = "LLMHighErrorRate"
      receiver: "slack"
    - matchers:
        - alertname = "LLMErrorTypeSpike"
      receiver: "slack"
    - matchers:
        - alertname = "LLMHighGPUMemoryUsage"
      receiver: "slack"
    - matchers:
        - alertname = "LLMHighCPUUsage"
      receiver: "slack"
    - matchers:
        - alertname = "LLMHighRAMUsage"
      receiver: "slack"
    - matchers:
        - alertname = "LLMLongQueueTime"
      receiver: "slack"
    - matchers:
        - alertname = "LLMLargeQueueSize"
      receiver: "slack"
    - matchers:
        - alertname = "LLMThrottlingIncidents"
      receiver: "slack"
    - matchers:
        - alertname = "LLMUserRateLimitBreaches"
      receiver: "slack"
    - matchers:
        - alertname = "LLMUserHighLatency"
      receiver: "slack"
    - matchers:
        - alertname = "LLMAbnormalTokenGeneration"
      receiver: "slack"
    - matchers:
        - alertname = "TstToggle"
      receiver: "slack"

receivers:
  - name: "null"
  - name: "slack"
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#ml-performance-optimizer'
        send_resolved: true
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: "{{ if eq .Status \"firing\" }}:fire:{{ else }}:white_check_mark:{{ end }} Alert: {{ index .CommonLabels.alertname }}"
        title_link: ""
        text: |
          *Status:* {{ .Status | toUpper }}

          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          {{ if .GeneratorURL }}*Link:* <{{ .GeneratorURL }}|View in Prometheus>{{ end }}
          ---
          {{ end }}
        short_fields: false
