apiVersion: v2
name: llm-monitoring
description: A Helm chart for deploying a FastAPI-based LLM inference app with Prometheus and Grafana monitoring
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: kube-prometheus-stack
    version: "45.7.1"
    repository: "https://prometheus-community.github.io/helm-charts"
