apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-monitoring-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: llm-monitoring
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - default
