project_id       = "coms6998-term-project"
region           = "us-east1"
zone			 = "us-east1-b"
cluster_name     = "llm-gke-cluster"
image_repository = "gcr.io/coms6998-term-project/llm-inference"
image_tag        = "latest"
